#!/bin/bash
# COMANDOS ÚTEIS - Firebase + React + Vite

echo "========================================"
echo "🚀 COMANDOS ÚTEIS DO PROJETO"
echo "========================================"
echo ""

echo "📦 INSTALAÇÃO E SETUP"
echo "─────────────────────"
echo "npm install                    # Instalar dependências"
echo "cp .env.example .env.local     # Copiar template de env"
echo "npm run dev                    # Iniciar dev server"
echo ""

echo "🏗️ BUILD E DEPLOY"
echo "─────────────────"
echo "npm run build                  # Build para produção"
echo "npm run preview                # Preview do build"
echo "firebase deploy                # Deploy no Firebase Hosting"
echo ""

echo "📁 ESTRUTURA DE ARQUIVOS"
echo "───────────────────────"
echo "# Ver estrutura criada:"
echo "tree src/"
echo "tree src/services/"
echo "tree src/hooks/"
echo "tree src/components/"
echo ""

echo "🔧 CONFIGURAÇÃO FIREBASE"
echo "───────────────────────"
echo "firebase init              # Inicializar Firebase no projeto"
echo "firebase login             # Fazer login"
echo "firebase deploy            # Deploy tudo"
echo "firebase emulators:start   # Iniciar emuladores locais"
echo ""

echo "✅ CHECKLIST DE SETUP"
echo "────────────────────"
echo "[ ] npm install"
echo "[ ] Criar projeto no Firebase Console"
echo "[ ] Habilitar Authentication (Email/Password)"
echo "[ ] Criar Firestore Database"
echo "[ ] cp .env.example .env.local"
echo "[ ] Preencher .env.local com credenciais"
echo "[ ] Importar firestore.rules no Firebase"
echo "[ ] npm run dev"
echo "[ ] Testar login e criar transação"
echo ""

echo "📝 ESTRUTURA DE PASTAS CRIADA"
echo "────────────────────────────"
echo "✅ src/firebase.js"
echo "✅ src/helpers/index.js"
echo "✅ src/hooks/useAuth.js"
echo "✅ src/services/users.js"
echo "✅ src/services/cards.js"
echo "✅ src/services/transactions.js"
echo "✅ src/components/CardsList.jsx"
echo "✅ src/components/TransactionsList.jsx"
echo "✅ src/components/UsersList.jsx"
echo "✅ firestore.rules"
echo "✅ .env.example"
echo "✅ App.jsx.example"
echo "✅ FIREBASE_SETUP.md"
echo "✅ PROJECT_STRUCTURE.md"
echo "✅ GUIA_FIREBASE.md"
echo ""

echo "🔐 SEGURANÇA"
echo "───────────"
echo "1. Firebase Console > Firestore > Rules"
echo "2. Copie conteúdo de 'firestore.rules'"
echo "3. Cole no editor de Rules"
echo "4. Clique 'Publish'"
echo "5. Pronto! Dados isolados por usuário"
echo ""

echo "💡 DICAS"
echo "───────"
echo "• Adicione credenciais do Firebase a .env.local"
echo "• NÃO compartilhe .env.local em repositórios"
echo "• Use .gitignore para excluir .env.local"
echo "• Testar no dev antes de fazer deploy"
echo "• Verificar firestore.rules antes de publicar"
echo ""

echo "📚 DOCUMENTAÇÃO"
echo "──────────────"
echo "Veja os arquivos:"
echo "• FIREBASE_SETUP.md       - Guia passo-a-passo"
echo "• PROJECT_STRUCTURE.md    - Detalhes técnicos"
echo "• GUIA_FIREBASE.md        - Referência rápida"
echo ""

echo "✨ Projeto pronto para usar!"
echo "========================================"
